### ISSUE TITLE
WebVR logo tracks head movement Up/Down, but not Left/Right

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/logo-experiments#11]
Currently [the WebVR logo](http://sparkbox.github.io/logo-experiments/webvr.html) responds to up/down motion, but will only move left/right if you drag on the touchscreen with your finger. Dragging up/down on the screen has no effect.

To reproduce the issue:

1. Browse to http://sparkbox.github.io/logo-experiments/webvr.html on a modern smartphone
2. Tap the "goggles icon" to switch to VR mode, and rotate your phone to landscape mode.
3. Rotate your phone left/right and confirm that the environment responds.
4. Rotate your phone up/down. Notice that the environment does not respond.

Fixing this may be as simple as reading the [AFrame](https://aframe.io/) docs and seeing if this is an intended behavior or common issue.

**Comment by andyli** [comment]
The aframe `look-controls` component indeed limited to y-axis rotation for touch interaction:
https://github.com/aframevr/aframe/blob/v0.7.0/src/components/look-controls.js#L328-L343

"Fixing" this will require writing a custom touch handler or using a 3rd-party component.

**Comment by bryanbraun** [comment]
@andyli, good find. It looks like this is a deliberate design decision, and it's based on the capabilities of the device it's being tested on: https://github.com/aframevr/aframe/issues/2557. Y-axis rotation works fine for devices that support gyro-orientation.

Thanks for investigating... I'll close this as wontfix.
