### ISSUE TITLE
The Web Component Logo is Broken

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/logo-experiments#13]
Here's what it looks like (not displaying at all—note the JS error at the bottom):

![image](https://user-images.githubusercontent.com/1256329/80502393-93456e00-893e-11ea-9e0a-57c77c255cfd.png)

Most likely the web-components API has shifted.

A fix for this would ideally:
- Work in all modern browsers (perhaps by using a polyfill?)
- Not use the "light/dark" logo style toggle (the dark style isn't really being used on the seesparkbox site anymore).

**Comment by changangus** [comment]
Hi, could I be assigned to this issue?

**Comment by bryanbraun** [comment]
@changangus sure thing! Assigning you now. 👍

**Comment by changangus** [comment]
Great! I'll get started
