### ISSUE TITLE
Add documentation on how to contribute

### ISSUE THREAD

**Issue by heatherdesigns** [sparkbox/logo-experiments#15]
Add a `contributing.md` file with information on how to contribute.

Things that can be included:
* Development workflow
* Steps to submit a PR
* Commit Style

Repos with example documentation:
[stylelin-config-sparkbox](https://github.com/sparkbox/stylelint-config-sparkbox/blob/master/CONTRIBUTING.md)

**Comment by MukulTan10** [comment]
hey, can i work on this , i am new to open source would be good for first timer as me

**Comment by bryanbraun** [comment]
Hey @MukulTan10, I can assign this one to you. 👍

**Comment by bryanbraun** [comment]
#16 was merged. Thanks for contributing!
