### ISSUE TITLE
CSS Masking Logo Broken in Chrome

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/logo-experiments#6]
To see what I mean by "broken" here's a gif of the behavior in Safari on the left (good) and Chrome on the right (bad):

![clipping-bug](https://cloud.githubusercontent.com/assets/1256329/19328877/dd27d46e-90a3-11e6-9f90-61002d838ba0.gif)

It used to work in Chrome, but I'm guessing a recent Chrome update broke it. (I'm seeing the broken behavior on Chrome 53.0.2785, on MacOS Sierra)

**Comment by pixelasticity** [comment]
The same "broken" behavior can be seen in Firefox.

**Comment by agriffis** [comment]
@bryanbraun did you see #7?

**Comment by bryanbraun** [comment]
@agriffis, ah yes, thanks for the reminder. Looking at it now. 👍
