### ISSUE TITLE
Optimize SVGs

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/logo-experiments#9]
The SVGs in this repo should be optimized. Maybe the easiest way is to run them through [SVG-OMG](https://jakearchibald.github.io/svgomg/).

**Comment by roboflank** [comment]
@bryanbraun Intrested.
Any specific SVG?

**Comment by bryanbraun** [comment]
Hi @denzelwamburu, 👋 .

The default settings at https://jakearchibald.github.io/svgomg/ are probably good enough. 👍

**Comment by ab-decoded** [comment]
can I take this one?

**Comment by bryanbraun** [comment]
Fixed by https://github.com/sparkbox/logo-experiments/pull/10. Closing.
